global using System.Runtime.InteropServices;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using System.Text;
global using System.Threading.Tasks;
global using Dalamud.Plugin;
global using ImGuiNET;
global using ECommons.DalamudServices;
global using Dalamud.Interface;
global using Dalamud.Interface.Colors;
global using Dalamud.Interface.Windowing;
global using ECommons.Logging;
global using ECommons;
global using static ECommons.GenericHelpers;
global using System.Numerics;
global using ECommons.ImGuiMethods;
global using ECommons.Schedulers;
global using static AutoRetainer.AutoRetainer;
global using AutoRetainer.Structs;
global using CSFramework = FFXIVClientStructs.FFXIV.Client.System.Framework.Framework;